### ISSUE TITLE
Check index.js if given path is a directory

### ISSUE THREAD

**Issue by yesmeck** [jshanson7/babel-resolver#4] opened 2016-01-03 19:47 UTC
I have a folder named `redux`  which is same as a package's name. I think `import * from redux` should be resolved to `node_modules` since there's no `index.js` under my `redux` folder.

**Comment by jshanson7** [comment] 2016-01-04 19:19
That's strange -- the plugin should always return a `node_modules` path if one exists.  Only after it checks `node_modules` will it look for a valid path within the resolved directories.  It should work the same as setting `NODE_PATH`.  Can you provide an example of how you got this error?

**Comment by yesmeck** [comment] 2016-01-05 03:23
I'm using babel with mocha. I create a sample repo to show this problem https://github.com/yesmeck/babel-resolver-bug . Try run `npm test`

**Comment by jshanson7** [comment] 2016-01-06 00:59
Good catch, the issue should be fixed for now...  The problem is `ResolverPlugin` needs a good way to find the project's root path.  Right now I have it traversing up from `babelOpts.filename` looking for a directory that contains `node_modules`, and then using that directory as the base from which `resolveDirs` are relative.  This is definitely not optimal, I'll be looking for better ways to do this.

**Closed as completed by jshanson7** 2016-01-06 00:59 UTC

**Comment by yesmeck** [comment] 2016-01-06 05:35
It works for me now, thanks.
